replicaCount: 2

image:
  repository: your-docker-repo/springboot-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: springboot.example.com
  path: "/"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}